services:
  xwiki:
    image: xwiki:lts-mariadb-tomcat
    restart: unless-stopped
    ports:
      - "8088:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - xwiki-data:/usr/local/xwiki

  mariadb:
    image: mariadb:12
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  xwiki-data:
  mariadb-data:
